Repository kube-green/kube-green, pull requests merged in 2024-04, with the labels that each got.

#310 Helm Chart Support
  charts/README.md
  charts/kube-green/.helmignore
  charts/kube-green/Chart.yaml
  charts/kube-green/templates/NOTES.txt
  charts/kube-green/templates/_helpers.tpl
  charts/kube-green/templates/certificate.yaml
  charts/kube-green/templates/cluster_role.yaml
  charts/kube-green/templates/cluster_role_binding.yaml
  charts/kube-green/templates/configmap.yaml
  charts/kube-green/templates/crds.yaml
  charts/kube-green/templates/deployment.yaml
  charts/kube-green/templates/role.yaml
  charts/kube-green/templates/service-account.yaml
  charts/kube-green/templates/service.yaml
  charts/kube-green/values.yaml
Labels: enhancement, deploy

#413 fix: enforce envtest cleanup
  internal/controller/sleepinfo/main_test.go
  internal/controller/sleepinfo/resource/ssa_integration_test.go
  internal/controller/sleepinfo/sleepinfo_test.go
  internal/controller/sleepinfo/testenvsetup_test.go
  internal/testutil/testenv.go
Labels: bug

#417 Deployment and cronjob managed with patches strategy
  .github/workflows/test.yml
  .vscode/settings.json
  Dockerfile
  Makefile
  api/v1alpha1/defaultpatches.go
  api/v1alpha1/sleepinfo_types.go
  api/v1alpha1/sleepinfo_types_test.go
  api/v1alpha1/sleepinfo_webhook_test.go
  internal/controller/sleepinfo/cronjobs/cronjobs.go
  internal/controller/sleepinfo/cronjobs/cronjobs_test.go
  internal/controller/sleepinfo/deployments/deployments.go
  internal/controller/sleepinfo/deployments/deployments_test.go
  internal/controller/sleepinfo/deployments/testutil.go
  internal/controller/sleepinfo/internal/mocks/cronjob.go
  internal/controller/sleepinfo/jsonpatch/jsonpatch_test.go
  internal/controller/sleepinfo/resources.go
  internal/controller/sleepinfo/resources_test.go
  internal/controller/sleepinfo/secrets.go
  internal/controller/sleepinfo/secrets_test.go
  internal/controller/sleepinfo/sleepinfo_controller.go
  internal/controller/sleepinfo/sleepinfo_test.go
  internal/controller/sleepinfo/sleepinfodata.go
  internal/controller/sleepinfo/sleepinfodata_test.go
  internal/controller/sleepinfo/testenvsetup_test.go
  internal/controller/sleepinfo/util_test.go
  tests/e2e/jsonpatch/01-assert-sleep.yaml
  tests/e2e/update-sleepinfo-only-wakeup.sh
  tests/e2e/wakeup-with-old-secret-format/00-assert.yaml
  tests/e2e/wakeup-with-old-secret-format/00-setup-resources.yaml
  tests/e2e/wakeup-with-old-secret-format/01-add-sleepinfo.yaml
  tests/e2e/wakeup-with-old-secret-format/02-assert-wakeup.yaml
  tests/e2e/wakeup-with-old-secret-format/02-wait.yaml
Labels: enhancement
