Repository kube-green/kube-green, pull requests merged in 2024-10, with the labels that each got.

#418 Feat/helm chart ci
  .github/configs/ct.yaml
  .github/configs/lintconf.yaml
  .github/workflows/helm.yaml
  Makefile
  charts/kube-green/Chart.yaml
  charts/kube-green/README.md
  charts/kube-green/values.yaml
Labels: enhancement, helm-chart

#454 remove watch cache on secrets
  Makefile
  README.md
  cmd/main.go
  internal/controller/sleepinfo/secrets.go
  internal/controller/sleepinfo/secrets_test.go
  internal/controller/sleepinfo/sleepinfo_controller.go
  internal/controller/sleepinfo/sleepinfo_test.go
  tests/integration/kuttl_test.go
  tests/integration/main_test.go
Labels: enhancement

#485 upgrade deps
  .github/workflows/community-operators.yml
  .github/workflows/helm.yaml
  .github/workflows/test.yml
  .golangci.yaml
  Dockerfile
  Makefile
  api/v1alpha1/sleepinfo_types.go
  api/v1alpha1/sleepinfo_webhook_test.go
  bundle/manifests/kube-green.clusterserviceversion.yaml
  charts/kube-green/README.md
  charts/kube-green/values.yaml
  charts/snapshots/test-output.snap.yaml
  config/default/manager_auth_proxy_patch.yaml
  go.mod
  go.sum
  internal/controller/sleepinfo/jsonpatch/jsonpatch.go
  internal/controller/sleepinfo/schedule_test.go
  internal/controller/sleepinfo/sleepinfo_test.go
  internal/controller/sleepinfo/util_test.go
  tests/integration/kuttl_test.go
Labels: dependencies
