Repository kube-green/kube-green, pull requests merged in 2025-01, with the labels that each got.

#504 remove kube-rbac-proxy
  .github/workflows/test.yml
  .golangci.yaml
  Makefile
  api/v1alpha1/sleepinfo_types.go
  bundle/manifests/kube-green-manager-config_v1_configmap.yaml
  charts/kube-green/README.md
  charts/kube-green/templates/_metrics.tpl
  charts/kube-green/templates/cert-manager.yaml
  charts/kube-green/templates/certificate.yaml
  charts/kube-green/templates/cluster_role.yaml
  charts/kube-green/templates/cluster_role_binding.yaml
  charts/kube-green/templates/configmap.yaml
  charts/kube-green/templates/crds/sleepinfo.yaml
  charts/kube-green/templates/deployment.yaml
  charts/kube-green/templates/hooks/metrics-cert/metrics-job-cert-gen.yaml
  charts/kube-green/templates/hooks/metrics-cert/role.yaml
  charts/kube-green/templates/hooks/metrics-cert/rolebinding.yaml
  charts/kube-green/templates/hooks/metrics-cert/service-account.yaml
  charts/kube-green/templates/hooks/webhook-cert/clusterrole.yaml
  charts/kube-green/templates/hooks/webhook-cert/clusterrolebinding.yaml
  charts/kube-green/templates/hooks/webhook-cert/role.yaml
  charts/kube-green/templates/hooks/webhook-cert/rolebinding.yaml
  charts/kube-green/templates/hooks/webhook-cert/service-account.yaml
  charts/kube-green/templates/hooks/webhook-cert/webhook-job-cert-gen.yaml
  charts/kube-green/templates/hooks/webhook-cert/webhook-job-cert-patch.yaml
  charts/kube-green/templates/service.yaml
  charts/kube-green/values.schema.json
  charts/kube-green/values.yaml
  charts/snapshots/test-output.snap.yaml
  cmd/main.go
  config/certmanager/certificate-metrics.yaml
  config/certmanager/certificate-webhook.yaml
  config/certmanager/certificate.yaml
  config/certmanager/issuer.yaml
  config/certmanager/kustomization.yaml
  config/crd/bases/kube-green.com_sleepinfos.yaml
  config/default/cert_metrics_manager_patch.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/default/manager_metrics_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/default/metrics_service.yaml
  config/manager/manager.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/prometheus/monitor_tls_patch.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/metrics_auth_role.yaml
  config/rbac/metrics_auth_role_binding.yaml
  config/rbac/metrics_reader_role.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/sleepinfo/sleepinfo_controller.go
  tests/integration/main_test.go
Labels: enhancement, breaking-change

#518 olm bundle can be installed in any namespace
  Makefile
  bundle/manifests/kube-green-aggregate-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/kube-green-controller-manager-metrics-service_v1_service.yaml
  bundle/manifests/kube-green-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/kube-green-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/kube-green-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/kube-green.clusterserviceversion.yaml
  bundle/manifests/kube-green.com_sleepinfos.yaml
  config/default/kustomization.yaml
  config/network-policy/allow-metrics-traffic.yaml
  config/network-policy/allow-webhook-traffic.yaml
  config/network-policy/kustomization.yaml
Labels: deploy

#511 Add dynamic MaxConcurrentReconciles
  cmd/main.go
  internal/controller/sleepinfo/secrets_test.go
  internal/controller/sleepinfo/sleepinfo_controller.go
  internal/controller/sleepinfo/sleepinfo_test.go
Labels: enhancement

#519 upgrade deps
  Dockerfile
  go.mod
  go.sum
Labels: dependencies

#520 breaking: removed support before k8s 1.26
  .github/workflows/helm.yaml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: breaking-change
